### ISSUE TITLE
prototype function arguments are incorrect

### ISSUE THREAD

**Issue by simonporter007** [jdthorpe/winston-log-and-exit#1]
Hi hi hi,

the arguments on the prototype logAndExit method are incorrect, which made it fail on my own instantiated winston logger. Specifically (line 51):
`function(level,msg,code)`
should be
`function(level,msg,code_or_callback)`
I think.

Cheers,

**Comment by jdthorpe** [comment]
Fixed in npm version v1.0.6

**Comment by simonporter007** [comment]
many thanks!
