### ISSUE TITLE
Process does not appear to exit as expected

### ISSUE THREAD

**Issue by jonathanmedd** [jdthorpe/winston-log-and-exit#3]
Looking to use this module to get around the issue of log info not being flushed to disk before process.exit() occurs. However, in the below sample code this line ```logger.log_and_exit('error','You must create a config file',1)``` should I believe result in the application exiting before reaching the final log message ```logger.info('Test log message 2')``` if ```config.json``` does not exist.

```
const fs = require('fs')
const winston = require('winston')
require('winston-log-and-exit')

const logger = new (winston.Logger)({
    transports: [
      new (winston.transports.Console)({
          level: 'info',
          colorize: true,
          handleExceptions: true,
          prettyPrint: true
      }),
      new (winston.transports.File)({
          name: 'f1',
          filename: "logs/error.log",
          level: 'error'
      }),
      new (winston.transports.File)({
          name: 'f2',
          filename: "logs/info.log",
          level: 'info'
      })
    ]
  })

  logger.info('Test log message 1')

  if (fs.existsSync('./config.json')) {
    var config = require('./config.json');
  }
  else {
    logger.log_and_exit('error','You must create a config file',1)
  }

  logger.info('Test log message 2')
```

However, the resulting entries in the log file, show that ```Test log message 2``` is still being written.

```
{"level":"info","message":"Test log message 1","timestamp":"2018-05-25T09:36:56.378Z"}
{"level":"error","message":"You must create a config file","timestamp":"2018-05-25T09:36:56.380Z"}
{"level":"info","message":"Test log message 2","timestamp":"2018-05-25T09:36:56.381Z"}
```

Am I implementing something incorrectly? I would expect the application to exit before reaching that final line.

**Comment by jdthorpe** [comment]
I think you misunderstand the purpose of winston-log-and-exit.   This plugin simply adds the guarantee that messages logged to asynchronous loggers are flushed before exiting.  In particular, logging to winston and then calling `process.exit(1);` would **likely** fail to log your prior messages to file.    

Your code above is running synchronously, which is outside the scope of this plugin.  If you want the behavior you are expecting, throw an error after calling `logger.log_and_exit()` to prevent the remaining synchronous code from running.
